server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cliente_cad?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
    
  jpa:
    hibernate:
      ddl-auto: update
